### ISSUE TITLE
alpha5 - System.NullReferenceException   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateSensors()

### ISSUE THREAD

**Issue by cagnulein** [hexagon-oss/openhardwaremonitor#15]
hi @pgrawehr thanks for the feedback. You were right, in the event viewer i found this:

<pre>Nome registro: Application
Origine:       .NET Runtime
Data:          02/09/2021 08:09:58
ID evento:     1026
Categoria attività:Nessuna
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      TestRigScadaCE
Descrizione:
Application: OpenHardwareMonitor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateSensors()
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric..ctor(System.String, OpenHardwareMonitor.Hardware.HDD.NVMeInfo, Int32, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateInstance(OpenHardwareMonitor.Hardware.HDD.StorageInfo, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.AbstractStorage.CreateInstance(Int32, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.HarddriveGroup..ctor(OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.Computer.set_HDDEnabled(Boolean)
   at OpenHardwareMonitor.GUI.MainForm.<.ctor>b__38_18(System.Object, System.EventArgs)
   at OpenHardwareMonitor.GUI.UserOption.add_Changed(System.EventHandler)
   at OpenHardwareMonitor.GUI.MainForm..ctor()
   at OpenHardwareMonitor.Program.Main(System.String[])

XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-02T06:09:58.412949200Z" />
    <EventRecordID>25009</EventRecordID>
    <Channel>Application</Channel>
    <Computer>TestRigScadaCE</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: OpenHardwareMonitor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateSensors()
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric..ctor(System.String, OpenHardwareMonitor.Hardware.HDD.NVMeInfo, Int32, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateInstance(OpenHardwareMonitor.Hardware.HDD.StorageInfo, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.AbstractStorage.CreateInstance(Int32, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.HarddriveGroup..ctor(OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.Computer.set_HDDEnabled(Boolean)
   at OpenHardwareMonitor.GUI.MainForm.&lt;.ctor&gt;b__38_18(System.Object, System.EventArgs)
   at OpenHardwareMonitor.GUI.UserOption.add_Changed(System.EventHandler)
   at OpenHardwareMonitor.GUI.MainForm..ctor()
   at OpenHardwareMonitor.Program.Main(System.String[])

</Data>
  </EventData>
</Event></pre>

With CrystalDiskInfo i saw the sensors correctly

_Originally posted by @cagnulein in https://github.com/hexagon-oss/openhardwaremonitor/issues/9#issuecomment-911242458_

**Comment by pgrawehr** [comment]
@cagnulein I've got a clue what could be wrong, but need some additional information. Can you please check whether you have any files named "OHM*.log" in your temp folder and attach them, if any?

**Comment by cagnulein** [comment]
[OHM_2021-09-02.log](https://github.com/hexagon-oss/openhardwaremonitor/files/7103665/OHM_2021-09-02.log)
@pgrawehr

**Comment by pgrawehr** [comment]
Could you please try this build and send me the log file? It should not crash any more, but probably will show your drive as generic only. Looks like your drive is not supporting any of the APIs OHM is trying to use.

[OpenHardwareMonitor-v0.9.7-alpha07-Debug.zip](https://github.com/hexagon-oss/openhardwaremonitor/files/7103700/OpenHardwareMonitor-v0.9.7-alpha07-Debug.zip)

**Comment by cagnulein** [comment]
@pgrawehr unfortunately it still crash
[OHM_2021-09-02.log](https://github.com/hexagon-oss/openhardwaremonitor/files/7103738/OHM_2021-09-02.log)

**Comment by pgrawehr** [comment]
Try this one instead

[OpenHardwareMonitor-v0.9.7-alpha07-Debug2.zip](https://github.com/hexagon-oss/openhardwaremonitor/files/7103897/OpenHardwareMonitor-v0.9.7-alpha07-Debug2.zip)

**Comment by cagnulein** [comment]
@pgrawehr this one works! and i saw the temperatures! wow! do you need something about this?

**Comment by pgrawehr** [comment]
Yes, please still send me the logfile and a screenshot, so I can confirm it takes the path it's supposed to.

**Comment by cagnulein** [comment]
![Untitled](https://user-images.githubusercontent.com/48216/131966790-388afd49-2144-46db-8627-bb81521a658e.png)
[OHM_2021-09-03.0.log](https://github.com/hexagon-oss/openhardwaremonitor/files/7103992/OHM_2021-09-03.0.log)
[OHM_2021-09-03.1.log](https://github.com/hexagon-oss/openhardwaremonitor/files/7103993/OHM_2021-09-03.1.log)
[OHM_2021-09-03.log](https://github.com/hexagon-oss/openhardwaremonitor/files/7103994/OHM_2021-09-03.log)

**Comment by pgrawehr** [comment]
This is quite an unusual configuration, and there are some inherent problems with having multiple disks with different hardware interfaces due to the way they are internally addressed. But good that it works for you now. I'll create a release build later.

**Comment by cagnulein** [comment]
yes it's an industrial PC :) thanks again for your effort!
